### ISSUE TITLE
Value cannot be null

### ISSUE THREAD

**Issue by ozzy-ext** [mylab-tools/apiclient#10]
```
 Message: Value cannot be null. (Parameter 'source')
    StackTrace: >2-
         at MyLab.ApiClient.BinaryHttpContentFactory.Create(Object source)
         at MyLab.ApiClient.ContentParameterApplier.Apply(HttpRequestMessage request)
         at MyLab.ApiClient.ApiRequestBase`1.ApplyParameters(HttpRequestMessage reqMsg)
         at MyLab.ApiClient.ApiRequestBase`1.SendRequestAsync(CancellationToken cancellationToken)
         at MyLab.ApiClient.ApiRequestBase`1.GetDetailedAsync(CancellationToken cancellationToken)
         at MyLab.ApiClient.ApiRequest`1.GetDetailedAsync(CancellationToken cancellationToken)
         at MyLab.ApiClient.ApiRequestExtensions.GetDetailedAsync[TRes](ApiRequest`1 req)
         at MyLab.ApiClient.ApiProxy`1.CallAndObserve[T](MethodInfo targetMethod, Object[] args)
         at Infonot.Message.Api.MessageSummaryComposer.ComposeAsync(Int32 id) in /builds/triasoft/infonot/message-api/src/Infonot.Message.Api/Stuff/MessageSummaryComposer.cs:line 45
         at Infonot.Message.Api.Services.DraftsService.GetHashInner(DataConnection db, Int32 messageId, SignHashAlgorythm alg) in /builds/triasoft/infonot/message-api/src/Infonot.Message.Api/Services/DraftsService.private.cs:line 346
         at Infonot.Message.Api.Services.DraftsService.GetHash2012(Int32 messageId, InfonotClientContext context) in /builds/triasoft/infonot/message-api/src/Infonot.Message.Api/Services/DraftsService.cs:line 188
         at Infonot.Message.Api.Controllers.DraftController.GetHash2012(InfonotClientContext context, Int32 messageId) in /builds/triasoft/infonot/message-api/src/Infonot.Message.Api/Controllers/Api/DraftsController.cs:line 140
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location where exception was thrown ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

**Comment by ozzy-ext** [comment]
notforme
